package com.cg.queries;

public interface QueryConstants {
	
	public static final String ADD_USERROLE = "INSERT INTO USERROLE VALUES(?,?,?,?,?)";
	
	public static final String ADD_POLICY = "INSERT INTO POLICY VALUES(?,?,?,?)";
	
	public static final String GET_ACCOUNTNUMBER_LIST_IN_ADMIN = "SELECT ACCOUNTNUMBER FROM USERROLE WHERE ROLECODE<>'ADM' AND ROLECODE<>'AGNT'";
	
	public static final String DISPLAY_CLAIM_DETAILS = "SELECT P.ACCOUNTNUMBER,P.POLICYNUMBER,C.CLAIMNUMBER,P.POLICYPREMIUM,P.POLICYTYPE,C.STATUS  FROM POLICY P, CLAIM C WHERE P.ACCOUNTNUMBER=? AND P.POLICYNUMBER=C.POLICYNUMBER"; 
	
	public static final String DISPLAY_CLAIM_DETAILS_ALL = "SELECT P.ACCOUNTNUMBER,P.POLICYNUMBER,C.CLAIMNUMBER,P.POLICYPREMIUM,P.POLICYTYPE,C.STATUS  FROM POLICY P, CLAIM C WHERE P.POLICYNUMBER=C.POLICYNUMBER";
	
	public static final String DISPLAY_CLAIM_DETAILS_AGENT = "SELECT P.ACCOUNTNUMBER,P.POLICYNUMBER,C.CLAIMNUMBER,P.POLICYPREMIUM,P.POLICYTYPE,C.STATUS  FROM POLICY P, CLAIM C WHERE P.ACCOUNTNUMBER=? AND P.POLICYNUMBER=C.POLICYNUMBER"; 
	
	public static final String DISPLAY_CLAIM_DETAILS_WITHOUT_ACCOUNTNUMBER = "SELECT P.ACCOUNTNUMBER,P.POLICYNUMBER,C.CLAIMNUMBER,P.POLICYPREMIUM,P.POLICYTYPE,C.STATUS  FROM POLICY P, CLAIM C WHERE P.POLICYNUMBER=C.POLICYNUMBER AND C.STATUS=?" ;
	
	public static final String DISPLAY_CLAIM_DETAILS_USING_STATUS = "SELECT P.ACCOUNTNUMBER,P.POLICYNUMBER,C.CLAIMNUMBER,P.POLICYPREMIUM,P.POLICYTYPE,C.STATUS  FROM POLICY P, CLAIM C WHERE P.ACCOUNTNUMBER=? AND C.STATUS=? AND P.POLICYNUMBER=C.POLICYNUMBER";
	
	public static final String DISPLAY_CLAIM_DETAILS_ALL_AGENT = "SELECT P.ACCOUNTNUMBER,P.POLICYNUMBER,C.CLAIMNUMBER,P.POLICYPREMIUM,P.POLICYTYPE,C.STATUS  FROM POLICY P, CLAIM C WHERE P.POLICYNUMBER=C.POLICYNUMBER AND P.ACCOUNTNUMBER=?";
	
	public static final String DISPLAY_CLAIM_DETAILS_WITHOUT_ACCOUNTNUMBER_AGENT = "SELECT P.ACCOUNTNUMBER,P.POLICYNUMBER,C.CLAIMNUMBER,P.POLICYPREMIUM,P.POLICYTYPE,C.STATUS  FROM POLICY P, CLAIM C WHERE P.ACCOUNTNUMBER=? AND P.POLICYNUMBER=C.POLICYNUMBER AND C.STATUS=? " ;
	
	public static final String UPDATE_STATUS = "UPDATE CLAIM SET STATUS=? WHERE CLAIMNUMBER=?";

	public static final String GET_ACCOUNTNUMBER_LIST_IN_AGENT = "SELECT ACCOUNTNUMBER FROM USERROLE WHERE AGENTID=?";
	
	public static final String GET_CLAIM_DETAILS_USING_ACCOUNTNUMBER = "SELECT * FROM POLICY WHERE ACCOUNTNUMBER=?";
	
	public static final String GET_ACCOUNTNUMBER_LIST_IN_AGENT_USING_USERNAME = "SELECT ACCOUNTNUMBER FROM USERROLE WHERE USERNAME=? AND AGENTID=?"; 
	
	public static final String ADD_CLAIM = "INSERT INTO CLAIM VALUES(?,?,?,?,?,?,?,?,?,?)";
	
	public static final String GET_ACCOUNT_NUMBER_IN_USER = "SELECT ACCOUNTNUMBER FROM USERROLE WHERE USERNAME=?"; 
	
	public static final String GET_QUESTIONS = "SELECT QUESTIONID,QUESTION FROM QUESTIONS WHERE POLICYTYPE=?";
	
	public static final String ADD_POLICY_DETAILS = "INSERT INTO POLICYDETAILS VALUES(?,?,?,?)";
	
	public static final String GET_CLAIM_DETAILS_USING_CLAIMNUMBER = "SELECT *  FROM CLAIM WHERE CLAIMNUMBER=?";
	
	public static final String GET_USER_RESPONSES = "SELECT Q.QUESTION, P.ANSWER FROM QUESTIONS Q, POLICYDETAILS P WHERE CLAIMNUMBER=? AND Q.QUESTIONID=P.QUESTIONID";
	
	public static final String VALIDATE_CREDENTIALS = "SELECT * FROM USERROLE WHERE USERNAME=? AND PASSWORD=?";

	public static final String GET_ROLECODE = "SELECT ROLECODE FROM USERROLE WHERE USERNAME=?";
	
	public static final String CHECK_POLICY = "SELECT * FROM POLICY WHERE POLICYTYPE=? AND ACCOUNTNUMBER=?";
	
	public static final String CHECK_USER = "SELECT * FROM USERROLE WHERE USERNAME=? OR ACCOUNTNUMBER=?";
	
	public static final String GET_AGENTS = "SELECT USERNAME FROM USERROLE WHERE ROLECODE='agnt'";
	
	
	
}
